version: 2.1

jobs:
  init:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          command: |
            terraform -chdir==infrastructure/ init
  format:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Format Terraform Files
          command: |
            terraform -chdir=infrastructure/ fmt -recursive
  plan:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - run:
          name: Plan the Infrastructure
          command: |
            terraform -chdir=infrastructure/ plan

workflows:
  version: 2.1
  plan_approve_apply:
    jobs:
      - checkout
      - init:
          requires:
            - checkout
      - fmt:
          requires:
            - init
      - plan:
          requires:
            - fmt
      - wait-for-approval:
          type: approval
          requires:
            - plan
